# general parameters
trial_path:             logs
trial_name:             ppo_frozenlake
wandb:                  True
project_name:           cleanqrl

# ray tune parameters
ray_local_mode:         False
num_cpus:               12
num_gpus:               0
num_samples:            3
cpus_per_worker:        1
gpus_per_worker:        0

# environment parameters
env_id:   FrozenLake-v1
is_slippery: False

# algorithm parameters
agent:               ppo_quantum_discrete_state
total_timesteps:    200000
num_envs:           5
seed:               None
num_steps:          128
anneal_lr:          True
gamma:              0.99
gae_lambda:         0.95
num_minibatches:    4
update_epochs:      4
norm_adv:           True
clip_coef:          0.2
clip_vloss:         True
ent_coef:           0.01
vf_coef:            0.5
max_grad_norm:      0.5
target_kl:          None

lr_input_scaling:   #0.025
  - grid_search
  - float
  - [0.01, 0.025]  
lr_weights:         #0.025
  - grid_search
  - float
  - [0.01, 0.025]  
lr_output_scaling:   #0.1
  - grid_search
  - float
  - [0.05,0.1]
num_qubits:         4
num_layers:         5
state_encoding:     binary
device:             lightning.qubit
diff_method:        adjoint


cuda: False

