# general parameters
trial_path:             logs
trial_name:             reinforce_frozenlake
wandb:                  True
project_name:           cleanqrl

# ray tune parameters
ray_local_mode:         False
num_cpus:               32
num_gpus:               0
num_samples:            1
cpus_per_worker:        1
gpus_per_worker:        0

# environment parameters
env_id:   FrozenLake-v1
is_slippery: False

# algorithm parameters
agent:              reinforce_quantum_discrete_state
total_timesteps:    20000
lr_input_scaling:   # 0.025
  - grid_search
  - float
  - [0.00005, 0.00001]  
lr_weights:         #0.025
  - grid_search
  - float
  - [0.00005, 0.00001]  
lr_output_scaling:  
  - grid_search
  - float
  - [0.00005, 0.00001]  
num_envs:           1
seed:               None
gamma:              
  - grid_search
  - float
  - [0.9, 0.95, 0.99]
num_qubits:         4
num_layers:         5
state_encoding:     binary
device:             lightning.qubit
diff_method:        adjoint
cuda:               False
save_model:         False
