# general parameters
trial_path:             logs
trial_name:             reinforce_frozenlake
wandb:                  True
project_name:           cleanqrl

# ray tune parameters
ray_local_mode:         False
num_cpus:               12
num_gpus:               0
ray_num_trial_samples:  3
cpus_per_worker:        1
gpus_per_worker:        0

# environment parameters
env_id:   FrozenLake-v1

# algorithm parameters
agent:              reinforce_quantum_discrete_state
total_timesteps:    200000
lr_input_scaling:   #0.025
  - grid_search
  - float
  - [0.01, 0.0025]  
lr_weights:         #0.025
  - grid_search
  - float
  - [0.01, 0.0025]    
lr_output_scaling:  0.1    
num_envs:           2
seed:               None
gamma:              0.99
num_qubits:         4
num_layers:         5
state_encoding:     binary
device:             lightning.qubit
diff_method:        adjoint
cuda:               False
save_model:         False
