# general parameters
trial_path:             logs
trial_name:             dqn_frozenlake_classical
wandb:                  True
project_name:           cleanqrl

# ray tune parameters
ray_local_mode:         False
num_cpus:               1
num_gpus:               0
ray_num_trial_samples:  1
cpus_per_worker:        1
gpus_per_worker:        0

# environment parameters
env_id:   FrozenLake-v1
is_slippery:  False

# algorithm parameters
agent:                DQN_classical_discrete_state
total_timesteps:      200000
lr:                   2.5e-4
num_envs:           1
seed:               42
buffer_size:        10000
gamma:              0.99
tau:                1.0
target_network_frequency:   500
batch_size:         128
start_e:            1
end_e:              0.05
exploration_fraction:   0.5
learning_starts:        10000
train_frequency:        10
cuda:                   False
save_model:             True
