# general parameters
trial_path:             logs
trial_name:             ppo_cartpole_classical
wandb:                  True
project_name:           cleanqrl

# ray tune parameters
ray_local_mode:         False
num_cpus:               1
num_gpus:               0
num_samples:  1
cpus_per_worker:        1
gpus_per_worker:        0

# environment parameters
env_id:   CartPole-v1

# algorithm parameters
agent:               PPO_classical
total_timesteps:    200000
learning_rate:      0.005
num_envs:           2
seed:               42
num_steps:          128
anneal_lr:          True
gamma:              0.99
gae_lambda:         0.95
num_minibatches:    4
update_epochs:      4
norm_adv:           True
clip_coef:          0.2
clip_vloss:         True
ent_coef:           0.01
vf_coef:            0.5
max_grad_norm:      0.5
target_kl:          None
cuda: False
save_model: True
wandb: True


