# general parameters
trial_path:             logs
trial_name:             reinforce_frozenlake
wandb:                  True
project_name:           cleanqrl

# ray tune parameters
ray_local_mode:         False
num_cpus:               1
num_gpus:               0
ray_num_trial_samples:  1
cpus_per_worker:        1
gpus_per_worker:        0

# environment parameters
env_id:   FrozenLake-v1
is_slippery: False

# algorithm parameters
agent:              reinforce_classical_discrete_state
total_timesteps:    200000
lr:                 0.01 
num_envs:           5
seed:               42
gamma:              0.99
cuda:               False
save_model:         False
