# general parameters
trial_path:             logs
trial_name:             reinforce_acrobot_classical
wandb:                  True
project_name:           cleanqrl

# ray tune parameters
ray_local_mode:         False
num_cpus:               1
num_gpus:               0
ray_num_trial_samples:  1
cpus_per_worker:        1
gpus_per_worker:        0

# environment parameters
env_id:   Acrobot-v1

# algorithm parameters
agent:              REINFORCE_classical
total_timesteps:    200000
lr:                 0.0025
num_envs:           2
seed:               42
gamma:              0.99
cuda: False
save_model: True
