# general parameters
trial_path:             logs
trial_name:             ppo_cartpole
wandb:                  True

# environment parameters
env_id:              Knapsack-v1
num_items:          4
total_budget:       2

# algorithm parameters
env_wrapper:         arctan
agent:               PPO_quantum_jumanji
total_timesteps:    10000
num_envs:           1
num_steps:          128
anneal_lr:          True
gamma:              0.99
gae_lambda:         0.95
num_minibatches:    4
update_epochs:      4
norm_adv:           True
clip_coef:          0.2
clip_vloss:         True
ent_coef:           0.01
vf_coef:            0.5
max_grad_norm:      0.5
target_kl:          None

lr_input_scaling:   0.001    
lr_weights:   0.001    
lr_output_scaling:   0.1   
num_qubits:         4
num_layers:         5
ansatz:             hea
init_method:        uniform
observables:        global
device:             lightning.qubit
diff_method:        adjoint


cuda: False

