# general parameters
trial_path:             logs
trial_name:             ppo_cartpole
wandb:                  False

# ray tune parameters
ray_local_mode:         False
num_cpus:               4
num_gpus:               0
ray_num_trial_samples:  3
cpus_per_worker:        3
gpus_per_worker:        0

# environment parameters
env_id:              Maze-v0
num_cols:            4
num_rows:            4
# env_id:              Knapsack-v1
# num_items:          4
# total_budget:       2

# env_id:              TSP-v1
# num_cities:          4

# algorithm parameters
agent:               PPO_classical_jumanji
total_timesteps:    30000
learning_rate:      0.0001
  # - grid_search
  # - float
  # - [0.001, 0.0001]   # only if model is classical
num_envs:           1
num_steps:          128
anneal_lr:          False
gamma:              0.95
gae_lambda:         0.95
num_minibatches:    4
update_epochs:      4
norm_adv:           True
clip_coef:          0.2
clip_vloss:         True
ent_coef:           0.01
vf_coef:            0.5
max_grad_norm:      0.5
target_kl:          None
cuda: False
save_model: True


