tune_config:  
  trial_path: logs
  trial_name:  ppo_pendulum
  ray_local_mode: False
  num_cpus:       32
  num_gpus:       0
  method:         RL
  ray_num_trial_samples:  3
  cpus_per_worker:        6
  gpus_per_worker:        0

algorithm_config:
  env_id:   "Pendulum-v1"
  agent:               PPO_classical_continuous
  total_timesteps:    10000
  seed: 1
  learning_rate:      0.0003
    # - grid_search
    # - float 
    # - [0.001, 0.0001, 0.00001]    # only if model is classical
  num_envs:           1
  num_steps:          2048
  anneal_lr:          True
  gamma:              0.9
    # - grid_search
    # - float
    # - [0.95, 0.99]
  gae_lambda:         0.95
  num_minibatches:    32
  update_epochs:      10
  norm_adv:           True
  clip_coef:          0.2
  clip_vloss:         True
  ent_coef:           0.0
  vf_coef:            0.5
  max_grad_norm:      0.5
  target_kl:          None
  cuda: False
  save_model: True
  wandb: True



