# general parameters
trial_path:             logs
trial_name:             reinforce_cartpole
wandb:                  True

# ray tune parameters
ray_local_mode:         False
num_cpus:               4
num_gpus:               0
ray_num_trial_samples:  3
cpus_per_worker:        3
gpus_per_worker:        0

# algorithm parameters
env_id:   "CartPole-v1"
agent:              REINFORCE_classical
total_timesteps:    10_000
lr:      0.001    #
num_envs:           2
gamma:              0.99
cuda: False
save_model: True
