type:               maze
alg:                qbm
use_ray:            True
local_mode:         False
ray_logging_path:   logs
num_seeds:          5
runs_count:         1
training_type:      uniform_sampling # basic_rl_fixed_start                           # uniform_sweep, uniform_sampling, basic_rl_random, basic_rl_fixed_start
  # - grid_search
  # - string
  # # - [basic_rl_random, basic_rl_fixed_start] 
  # - [uniform_sweep, uniform_sampling]

mean: 0.0
variance: 0.1
action_size: 5
state_size: 15

layer:    [3,3]    
  # - grid_search
  # - list(int)
  # - [[4,4], [8,8]]
hamiltonian_type:  H_(d+1)_rep_5
  # - grid_search
  # - string
  # - [H_(d+1)_rep_2, H_(d+1)_rep_3]
sampler_type:      dwave-qpu
episode_length:     10
  # - grid_search
  # - int 
  # - [10, 20, 100]
training_steps:     200

env_type:           crawford #mueller_3x3 # mueller_3x3 #crawford #'mueller_3x3'
  # - grid_search
  # - string
  # - [mueller_3x3, crawford] #, neumann_a, neumann_b]
P:    -100
A:    1
W:    -1
R:    100
n:    3
  # - grid_search
  # - int
  # - [3, 4, 5, 6, 7, 8, 9, 10]

learning_rate:  0.001
  # - grid_search
  # - float
  # - [0.005, 0.0025, 0.001, 0.00075, 0.0005]

learning_rate_schedule:    [0.001, 1e-5, 200]


beta:         2.0
  # - grid_search
  # - float
  # - [1.0, 2.0, 3.0, 4.0, 5.0]
big_gamma:    0.5067013
  # - grid_search
  # - float
  # - [0.2, 0.5, 1.0, 2.0, 5.0]
small_gamma:  0.95
  # - grid_search
  # - float
  # - [0.8, 0.9, 0.95, 0.99]


# sampler_type:     dwave-qpu-SA #openjij-sqa-SA          #   openjij-sa-SA # dwave-qpu-SQA', 'dwave-sim-SQA', 'openjij-sa-SQA', 'openjij-sqa-SQA', 'openjij-csqa-SQA'simulator # dwave_embedding, dwave_fixed_embedding, simulator
#   # - grid_search
#   # - string
#   # - ['dwave-sim-SQA',  'openjij-sa-SQA', 'dwave-sim-SA', 'openjij-sa-SA']

openjij_sa:
  beta_min:   0.01
  beta_max:   2.0
  num_sweeps: 100

  # schedule:

openjij_sqa:
  beta:       2.0
  gamma:      20.0
  num_sweeps: 10
  trotter:    25
  # schedule:   False

openjij_csqa:
  beta:       2.0
  gamma:      0.5
  num_sweeps: 100
  # trotter:   10
  # schedule:

dwave_sim:
  beta_range:            [0.01, 2.0] # [2.0, 8.699514748210191]
  beta_schedule_type:    geometric
  num_sweeps:            100
  # num_sweeps_per_beta:            1

fixed_embedding:                  False
use_gauge: False
# anneal_schedule:    
#   - [0.0, 0.0]
#   - [20.0, 1.0]
num_reads:                        1000          # default is None
anneal_schedule: default
  # - anneal_time_list:  [10, 20, 50, 100]
  # - s_pause_list: [0.3, 0.4, 0.5]
  # - anneal_schedule_type_list: ['mid_anneal_pause', 'mid_anneal_quench']
answer_mode: raw
programming_thermalization:       0.0
readout_thermalization:           0.0
auto_scale:                       False          # default is True
reduce_intersample_correlation:   False
calculate_chain_strength:         True
prefactor_chain_strength:         2.0
return_embedding:                 False
embedding_path:                   embeddings     
embedding:
  max_no_improvement:             10
  random_seed:                    42

simulator_config:
  beta_range:                     [0.5, 100] # [2.0, 8.699514748210191]
  beta_schedule_type:             geometric
  #seed:                           42
  num_reads:                      1000
  num_sweeps:                     500
  # num_sweeps_per_beta:            1


